# Generated by Django 3.1.2 on 2021-05-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('cName', models.CharField(max_length=100)),
                ('sub', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
